// Generated by scripts/verified-standards-runtime/build.py. Do not edit.
export const VERIFIED_STANDARDS_SCHEMA_VERSION = "verified-residential-standards-runtime/v1" as const;
export const VERIFIED_STANDARDS_RELEASE_VERSION = "verified-residential-standards-v2-2026-09-24" as const;
export const VERIFIED_STANDARDS_RECORD_COUNT = 213 as const;
export const VERIFIED_STANDARDS_RECORD_IDS_SHA256 = "ae63136e2c3e1566d7b0111604eb82168a8bbbb4c2ae520dcb4bb8b641b53124" as const;
export const VERIFIED_STANDARDS_SOURCE_MANIFEST_SHA256 = "c225779da9eeb18c225185049c733ac62a420f31643137d75c7f096ea4901b11" as const;
export const VERIFIED_STANDARDS_BUNDLE_SHA256 = "023c530ce824fc6d59156b39a39ef2cc677ac44a36a574ccb466bf04099df659" as const;
